# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Create dummy env keys file if not exists, so that build won't fail
RUN mkdir -p src/env && echo "export const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';" > src/env/keys.ts

# Build the project
RUN npm run build

CMD [ "node", "build/index.js" ]
